### ISSUE TITLE
SAMD51 Metro on IttsyBittsy?

### ISSUE THREAD

**Issue by RandoSY** [wa1tnr/CamelForth-SAMD51-SAMD21#1]
Wondering if there is any issues running the Metro-51 image on the Adafruit IttsyBittsy?

  https://www.adafruit.com/product/3800

![3800-03](https://user-images.githubusercontent.com/609947/59869117-8fc97980-9360-11e9-99ba-2e9be29e3d13.jpg)

**Comment by wa1tnr** [comment]
Thanks for your interest.

I have not looked at this in a while; from what I saw today,
the program runs on Trellis M4 now.

Whatever was done most recently would have been to
that end: getting Trellis M4 running.

**Comment by wa1tnr** [comment]
Program should be ready for ItsyBitsyM4 now.

Branch 'master' is fine - did a quick merge of existing work,
into branch 'master'.

Let me know if this does not answer your inquiry!

As far as I could guess (quickly) no, the Metro M4 version would
not run well (if at all) on ItsyBitsyM4.

I didn't check, as I already knew there were similarities between
NeoTrellis M4 and ItsyBitsyM4, which was the approach used
today, to close this issue. ;)

Here is the latest commit relevant to this issue:

https://github.com/wa1tnr/CamelForth-SAMD51-SAMD21/commit/5a739e1a16b55c592d8cdab40f89089fa278ed7d#diff-1192848017f653c7822d453378e06ee2
